### ISSUE TITLE
ServiceHost close method

### ISSUE THREAD

**Issue by snovik** [MhAllan/TcpServiceCore#11]
ServiceRun

```
            ...
            Console.WriteLine("Start service on {0} port... ", 9091);
            await host.Open();
            Console.ReadLine();
            await host.Close(); 
            Console.WriteLine("Service stoped");
            }
```

This code generated error: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.<>c.<AcceptTcpClientAsync>b__24_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TcpServiceCore.Server.ServiceHost`1.<<OnOpen>b__9_0>d.MoveNext() in D:!WorkTest\ProxyServer\ProxyServer\ProxyServiceCore\src\TcpServiceCore\Server\ServiceHost.cs:line 57

in this code:
Service host   OnOpen()

```
                    ...
                    catch (Exception ex)
                    {
                        Global.ExceptionHandler?.LogException(ex);
                    }
```

**Comment by MhAllan** [comment]
That is normal and the exception is caught so it won't break the application. the logger I have now writes the exception to the console. The logger milestone is not done yet, you can ignore this log by setting Global.ExceptionHandler to null.
