### ISSUE TITLE
.NET Core 1.1 ChannelFactory.CreateProxy Fails

### ISSUE THREAD

**Issue by ByronAP** [MhAllan/TcpServiceCore#17]
```
var proxy = Activator.CreateInstance(ProxyType, innerProxy);
if (open)
      await ((IClientChannel) proxy).Open();
return (T) proxy;
```

can not cast the types

> {System.InvalidCastException: Unable to cast object of type 'ATOM.Test.TcpLibTest.IService_TcpServiceCoreProxy' to type 'TcpServiceCore.Client.IClientChannel'.
>    at TcpServiceCore.Client.ChannelFactory`1.<CreateProxy>d__6.MoveNext() in C:\Users\info\Documents\source\atom-backend\TcpServiceCore\Client\ChannelFactory.cs:line 50
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at TcpServiceCore.Client.ChannelFactory`1.<CreateProxy>d__5.MoveNext() in C:\Users\info\Documents\source\atom-backend\TcpServiceCore\Client\ChannelFactory.cs:line 33
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at ATOM.Test.TcpLibTest.Program.<RunExample>d__1.MoveNext() in C:\Users\info\Documents\source\atom-backend\ATOM.Test.TcpLibTest\Program.cs:line 39}

**Comment by ByronAP** [comment]
project.json for ref

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "TcpServiceCore": "1.0.0-*"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": "dnxcore50"
    }
  }
}
```

and the code is the demo

```
using System;
using System.Threading.Tasks;
using TcpServiceCore.Attributes;
using TcpServiceCore.Client;
using TcpServiceCore.Communication;
using TcpServiceCore.Dispatching;
using TcpServiceCore.Server;

namespace ATOM.Test.TcpLibTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            RunExample().Wait();
        }

        static async Task RunExample()
        {
            var config = new ChannelConfig
            {
                ReceiveTimeout = TimeSpan.FromSeconds(10),
                SendTimeout = TimeSpan.FromSeconds(10)
            };

            var host = new ServiceHost<Service>(9091);

            host.AddContract<IService>(config);

            host.ServiceInstantiated += s =>
            {
                //init created instances
            };

            await host.Open();

            var client = await ChannelFactory<IService>.CreateProxy("localhost", 9091, config);

            using ((IClientChannel)client)
            {
                var result = await client.Echo("message");
                Console.WriteLine(result);
            }

            Console.ReadLine();
        }
    }

    [ServiceContract]
    public interface IService
    {

        [OperationContract]
        Task<string> Echo(string msg);

        [OperationContract(IsOneWay = true)]
        Task FireMsg(string msg);
    }

    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single)]
    public class Service : IService
    {
        public Task<string> Echo(string msg)
        {
            return Task.FromResult(msg.ToUpper());
        }

        public Task FireMsg(string msg)
        {
            Console.WriteLine($"received {msg}");
            return Task.CompletedTask;
        }
    }
}
```
